:port: 8000
:address: 127.0.0.1

:initial_messages: 
 - /animata/layer/layer_0001/image jgb-doll2.png
 - /animata/move/joint head 10.0 10.0
 - /joint head  20.0 54.0
 - /anibone  bogus 0.4
 - /anibone  face 0.4
 - /layervis layer_0001 0
 - /layervis layer_0001 1
 - /layervis bogus 1
 - /layerpos layer_0001 100 40 
  


